import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import test from 'node:test';

const MANIFEST='docs/production-evidence/risk-lab/rbry11-phase-b5-manifest.json';
const INDEX='docs/production-evidence/risk-lab/rbry11-phase-b5/index.json';
const TEMP_WORKFLOW='.github/workflows/risk-lab-rbry11-retry.yml';
const TEMP_SCRIPT='scripts/risk-lab-retry-rbry11.mjs';
function stableValue(v){if(Array.isArray(v))return v.map(stableValue);if(!v||typeof v!=='object')return v;return Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,stableValue(x)]));}
function hash(v){return createHash('sha256').update(JSON.stringify(stableValue(v)),'utf8').digest('hex');}
function load(){const manifest=JSON.parse(readFileSync(MANIFEST,'utf8')),index=JSON.parse(readFileSync(INDEX,'utf8')),observations=[];for(const descriptor of index.observationFiles){const payload=JSON.parse(readFileSync(descriptor.file,'utf8'));assert.equal(payload.schemaVersion,1);assert.equal(payload.phase,'3.5-B5');assert.equal(payload.ticker,'RBRY11');assert.equal(payload.year,descriptor.year);assert.equal(payload.count,descriptor.count);assert.equal(payload.observations.length,descriptor.count);assert.equal(hash(payload.observations),descriptor.observationsHash);observations.push(...payload.observations);}return{manifest,index,observations};}

test('quatro arquivos anuais recompõem as 47 competências contínuas do RBRY11',()=>{const{manifest,index,observations}=load();assert.equal(index.status,'complete');assert.equal(index.identity.ticker,'RBRY11');assert.equal(index.identity.cnpj,'30166700000111');assert.deepEqual(index.observationFiles.map(x=>x.count),[12,12,12,11]);assert.equal(observations.length,47);assert.equal(hash(observations),index.combinedObservationsHash);assert.equal(index.combinedObservationsHash,manifest.deterministicHashes.combinedObservationsHash);const months=observations.map(x=>x.competenceMonth);assert.equal(months[0],'2022-01');assert.equal(months.at(-1),'2025-11');assert.equal(new Set(months).size,47);assert.deepEqual(index.result.missingMonths,[]);for(const o of observations){assert.equal(o.ticker,'RBRY11');assert.ok(o.amountPerShare>0);assert.match(o.sourceHash,/^[a-f0-9]{64}$/);assert.match(o.protocolHash,/^[a-f0-9]{64}$/);assert.equal(o.protocolEvidenceType,'official_manager_metadata');}});

test('hashes do retry, sanitização, caso, auditoria e índice são reproduzíveis',()=>{const{manifest,index,observations}=load();const casePayload={...index.caseWithoutObservations,observations};assert.equal(hash(casePayload),index.caseHash);const retryPayload={...index.retryAudit};delete retryPayload.auditHash;assert.equal(hash(retryPayload),index.retryAudit.auditHash);const sanPayload={...index.sanitization};delete sanPayload.sanitizationHash;assert.equal(hash(sanPayload),index.sanitization.sanitizationHash);const auditPayload={...index.audit};delete auditPayload.auditHash;assert.equal(hash(auditPayload),index.audit.auditHash);const evidence={...index};delete evidence.evidenceHash;assert.equal(hash(evidence),index.evidenceHash);assert.equal(index.evidenceHash,manifest.deterministicHashes.evidenceHash);});

test('duas execuções registradas têm hashes idênticos e classificação total',()=>{const{index}=load();assert.equal(index.execution.runs,2);assert.equal(index.execution.hashesMatch,true);assert.deepEqual(index.execution.run1,index.execution.run2);assert.equal(index.result.documentsDiscovered,54);assert.equal(index.result.documentsClassified,54);assert.equal(index.result.baselineCompletedDocuments,49);assert.equal(index.result.baselineRawObservations,49);assert.equal(index.result.retriedRawObservations,50);assert.equal(index.result.observationsAfterTemporalSanitization,49);assert.equal(index.result.selectedMonthlyObservations,47);assert.equal(index.result.pendingDocuments,0);assert.equal(index.result.conflicts,0);assert.equal(index.result.longestContiguousSequence,47);});

test('retentativa oficial recupera somente 987180 e preserva hashes oficiais',()=>{const{index,observations}=load();assert.equal(index.recoveries.length,1);const r=index.recoveries[0];assert.equal(r.documentId,'987180');assert.equal(r.classification,'recovered_transient_failure');assert.equal(r.competenceMonth,'2025-08');assert.equal(r.amountPerShare,1.25);assert.equal(r.retryArtifactId,8610152329);const o=observations.find(x=>x.documentId==='987180');assert.ok(o);assert.equal(o.informationDate,'2025-09-09');assert.equal(o.paymentDate,'2025-09-16');assert.equal(o.sourceHash,'ad593ddfdc91a65e3006cc5fec30a492cf260549531526b802d9dd79eadc827c');assert.equal(o.protocolHash,'00c7be71bcb5620b626f4a9dbc5652f33ce9b06cdc5db355a9ee548754503e35');});

test('quatro classes secundárias são auditadas sem observação econômica',()=>{const{index}=load();assert.deepEqual(index.retryAudit.secondaryShareClasses.map(x=>[x.documentId,x.parsedTicker]),[['300850','RBRY15'],['300852','RBRY14'],['300855','RBRY13'],['350224','RBRY13']]);});

test('sanitizador remove somente a deriva de virada de ano 254829',()=>{const{index,observations}=load();assert.equal(index.sanitization.exclusions.length,1);const x=index.sanitization.exclusions[0];assert.equal(x.documentId,'254829');assert.equal(x.reportedCompetenceMonth,'2022-12');assert.equal(x.correctedCompetenceMonth,'2021-12');assert.equal(observations.some(o=>o.documentId==='254829'),false);assert.equal(observations.find(o=>o.competenceMonth==='2022-12')?.documentId,'399753');});

test('duas reapresentações escolhem versão 2 deterministicamente',()=>{const{index,observations}=load();const bySelected=new Map(index.selectionDecisions.map(x=>[x.selectedDocumentId,x]));assert.equal(bySelected.get('427520')?.supersededDocuments[0].documentId,'427474');assert.equal(bySelected.get('1009923')?.supersededDocuments[0].documentId,'1009913');assert.equal(observations.find(o=>o.competenceMonth==='2023-02')?.documentId,'427520');assert.equal(observations.find(o=>o.competenceMonth==='2025-09')?.documentId,'1009923');assert.equal(observations.find(o=>o.competenceMonth==='2025-10')?.documentId,'1033803');});

test('não restam workflow temporário, script temporário, hardcode ou efeitos de produto',()=>{const{index}=load();assert.equal(existsSync(TEMP_WORKFLOW),false);assert.equal(existsSync(TEMP_SCRIPT),false);const auditor=readFileSync('src/lib/risk-lab/FrozenDividendRetryCheckpointAuditor.ts','utf8');const sanitizer=readFileSync('src/lib/risk-lab/FrozenDividendObservationWindowSanitizer.ts','utf8');assert.doesNotMatch(auditor,/RBRY11|987180|254829|300850/);assert.doesNotMatch(sanitizer,/RBRY11|987180|254829|300850/);assert.doesNotMatch(JSON.stringify(index),/premiumIntegrated|notificationsSent|productionEndpoint/i);});
